baseURL = "http://bettersoftware.in/"
languageCode = "en-us"
title = "Better Software"
theme = "ananke"

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]

  [[menu.main]]
    name = "Podcasts"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/categories/podcasts/"
    weight = -30

  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    pre = "<i class='fa fa-heart'></i>"
    url = "/categories/blogs/"
    weight = -10

  [[menu.main]]
    identifier = "About"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -1

[params]
  custom_css = ["css/custom.css"]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  linkedin = "www.linkedin.com"
  twitter = "https://twitter.com/GoHugoIO"