baseURL = "http://bettersoftware.in/"
languageCode = "en-us"
title = "Better Software"
theme = "ananke"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
  custom_css = ["css/custom.css"]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  body_classes = "inter bg-near-white"
  post_content_classes = "inter bg-white"